### **1. Simulate any random rectangular matrix A**

In [1]:
import numpy as np

mat = np.matrix(np.random.randint(low = 1, high=5, size = (4,4)))
display(mat)

matrix([[1, 1, 4, 1],
        [1, 3, 1, 3],
        [3, 1, 1, 1],
        [4, 3, 1, 4]])

- What is the rank and trace of A?


In [2]:
print(f"The rank of the matrix is {np.linalg.matrix_rank(mat)} and it's the maximum number of rows or columns linearly independent")

The rank of the matrix is 4 and it's the maximum number of rows or columns linearly independent


- What is the determinant of A?

In [3]:
print(f"The determinat of the matrix is {np.linalg.det(mat) :.1f}")

The determinat of the matrix is -28.0


- Can you invert A? How?

We can use np.linalg.inv to math it. If the determinat is different to zero, we can find the inverse matrix

In [4]:
if np.linalg.det(mat) != 0:
    print('The inverse matrix is:')
    display(np.linalg.inv(mat))
else:
    print(f"The inverse of the matrix doesn't exist, det(matrix) must be <> 0")


The inverse matrix is:


matrix([[-7.14285714e-02, -1.07142857e-01,  3.92857143e-01,
          1.11022302e-16],
        [-2.85714286e-01,  1.07142857e+00,  1.07142857e+00,
         -1.00000000e+00],
        [ 2.85714286e-01, -7.14285714e-02, -7.14285714e-02,
          2.27091073e-17],
        [ 2.14285714e-01, -6.78571429e-01, -1.17857143e+00,
          1.00000000e+00]])

- How are eigenvalues and eigenvectors of A’A and AA’ related? What interesting differences can you notice between both?

Eigenvalues

In [5]:
print("eigenvalues of A'A:")
display(np.linalg.eig(np.dot(mat.T, mat))[0])
print("eigenvalues of AA':")
display(np.linalg.eig(np.dot(mat, mat.T))[0])

eigenvalues of A'A:


array([75.53360026, 11.80694932,  5.49960254,  0.15984788])

eigenvalues of AA':


array([75.53360026, 11.80694932,  0.15984788,  5.49960254])

Note that eigenvalues are the same

Eigenvectors

In [6]:
print("eigenvectors of A'A")
display(np.linalg.eig(np.dot(mat.T, mat))[1])
print("eigenvectors of AA'")
display(np.linalg.eig(np.dot(mat, mat.T))[1])

eigenvectors of A'A


matrix([[ 0.55206249,  0.17543832, -0.81073646, -0.08458604],
        [ 0.49569682,  0.14878957,  0.44592753, -0.73027047],
        [ 0.3366986 , -0.94007653,  0.02066674,  0.04962916],
        [ 0.57978075,  0.25167275,  0.37871879,  0.67608223]])

eigenvectors of AA'


matrix([[ 0.34223129,  0.92674343,  0.14942695, -0.04118198],
        [ 0.47350024, -0.12710505, -0.49403893, -0.7180302 ],
        [ 0.35305042,  0.00387042, -0.64610024,  0.67667931],
        [ 0.73077402, -0.35351937,  0.5622736 ,  0.15761277]])

Eigenvectors are diferent

### **2. Add a steady, well-centered picture of your face to a shared folder alongside your classmates**